import { Product, Sale, PartnerUser, DailyCaisse } from '@/types/crm';

export const INITIAL_EXCHANGE_RATE = 242; // 1 USD = 242 DZD (Square Market Parallel Rate)

export const PARTNERS: PartnerUser[] = [
  { id: 'partner-1', name: 'Adem', avatarColor: 'bg-blue-600 text-white' },
  { id: 'partner-2', name: 'Abdou', avatarColor: 'bg-emerald-600 text-white' },
];

// Single official product: Jio AI Pro at 1,400 DZD
export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-jio-ai-pro',
    name: 'Jio AI Pro',
    category: 'AI Tools',
    defaultCostUsd: 0, // Pure net profit
    defaultSellingDzd: 1400,
    stockKeys: [
      'https://jioai.pro/activate?token=jio-vip-dz-01',
      'https://jioai.pro/activate?token=jio-vip-dz-02',
      'https://jioai.pro/activate?token=jio-vip-dz-03',
      'https://jioai.pro/activate?token=jio-vip-dz-04',
      'https://jioai.pro/activate?token=jio-vip-dz-05',
      'https://jioai.pro/activate?token=jio-vip-dz-06',
    ],
    stockItems: [
      { id: 'stk-1', keyOrLink: 'https://jioai.pro/activate?token=jio-vip-dz-01', addedAt: '2026-09-11T10:00:00Z' },
      { id: 'stk-2', keyOrLink: 'https://jioai.pro/activate?token=jio-vip-dz-02', addedAt: '2026-09-11T10:00:00Z' },
      { id: 'stk-3', keyOrLink: 'https://jioai.pro/activate?token=jio-vip-dz-03', addedAt: '2026-09-11T10:00:00Z' },
      { id: 'stk-4', keyOrLink: 'https://jioai.pro/activate?token=jio-vip-dz-04', addedAt: '2026-09-11T10:00:00Z' },
      { id: 'stk-5', keyOrLink: 'https://jioai.pro/activate?token=jio-vip-dz-05', addedAt: '2026-09-11T10:00:00Z' },
      { id: 'stk-6', keyOrLink: 'https://jioai.pro/activate?token=jio-vip-dz-06', addedAt: '2026-09-11T10:00:00Z' },
    ],
    lowStockThreshold: 2,
    description: 'Abonnement officiel VIP Jio AI Pro (Accès complet intelligence artificielle).',
    createdAt: '2026-09-01T10:00:00Z',
  },
];

// Up-to-date real sales for Jio AI Pro:
// 1) BaridiMob capital: exactly 22,345 DZD in net profit across past 2 days (Sept 10 & 11)
// 2) 7 unconfirmed waiting payments ("Pay Later / Crédit") for Jio AI Pro at 1,400 DZD
export const INITIAL_SALES: Sale[] = [
  // --- Sept 10, 2026 (Day 1: 5,600 DA BaridiMob Profit - 4 sales of Jio AI Pro @ 1400 DA) ---
  {
    id: 'sale-jio-101',
    saleNumber: '#1001',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Kamel T.',
    customerPhone: '+213550123456',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-101',
    exchangeRateUsed: 242,
    createdAt: '2026-09-10T11:20:00.000Z',
  },
  {
    id: 'sale-jio-102',
    saleNumber: '#1002',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Abdou',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Bilel M.',
    customerPhone: '+213661234567',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-102',
    exchangeRateUsed: 242,
    createdAt: '2026-09-10T14:15:00.000Z',
  },
  {
    id: 'sale-jio-103',
    saleNumber: '#1003',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Samir B.',
    customerPhone: '+213770345678',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-103',
    exchangeRateUsed: 242,
    createdAt: '2026-09-10T17:40:00.000Z',
  },
  {
    id: 'sale-jio-104',
    saleNumber: '#1004',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Abdou',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Rachid K.',
    customerPhone: '+213552456789',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-104',
    exchangeRateUsed: 242,
    createdAt: '2026-09-10T20:30:00.000Z',
  },

  // --- Sept 11, 2026 (Day 2: 16,745 DA BaridiMob Profit - 11 sales @ 1400 DA + 1 @ 1345 DA = 22,345 DA total) ---
  {
    id: 'sale-jio-105',
    saleNumber: '#1005',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Moncef D.',
    customerPhone: '+213663567890',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-105',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T09:15:00.000Z',
  },
  {
    id: 'sale-jio-106',
    saleNumber: '#1006',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Abdou',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Hichem L.',
    customerPhone: '+213774678901',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-106',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T10:30:00.000Z',
  },
  {
    id: 'sale-jio-107',
    saleNumber: '#1007',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Tarek F.',
    customerPhone: '+213555789012',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-107',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T11:45:00.000Z',
  },
  {
    id: 'sale-jio-108',
    saleNumber: '#1008',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Abdou',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Anis V.',
    customerPhone: '+213666890123',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-108',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T13:20:00.000Z',
  },
  {
    id: 'sale-jio-109',
    saleNumber: '#1009',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Youcef Z.',
    customerPhone: '+213777901234',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-109',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T14:40:00.000Z',
  },
  {
    id: 'sale-jio-110',
    saleNumber: '#1010',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Abdou',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Nadia S.',
    customerPhone: '+213558012345',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-110',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T16:10:00.000Z',
  },
  {
    id: 'sale-jio-111',
    saleNumber: '#1011',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Mehdi C.',
    customerPhone: '+213669123456',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-111',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T17:35:00.000Z',
  },
  {
    id: 'sale-jio-112',
    saleNumber: '#1012',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Abdou',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Mourad E.',
    customerPhone: '+213780234567',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-112',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T19:00:00.000Z',
  },
  {
    id: 'sale-jio-113',
    saleNumber: '#1013',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Hakim G.',
    customerPhone: '+213561345678',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-113',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T20:25:00.000Z',
  },
  {
    id: 'sale-jio-114',
    saleNumber: '#1014',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Abdou',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Reda M.',
    customerPhone: '+213672456789',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-114',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T21:40:00.000Z',
  },
  {
    id: 'sale-jio-115',
    saleNumber: '#1015',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Zaki O.',
    customerPhone: '+213778567890',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-115',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T22:20:00.000Z',
  },
  {
    id: 'sale-jio-116',
    saleNumber: '#1016',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1345, // Ajustement exact solde BaridiMob -> 22,345 DA
    productCostUsd: 0,
    netProfitDzd: 1345,
    soldBy: 'Abdou',
    paymentMethod: 'baridimob',
    paymentStatus: 'paid',
    customerName: 'Fares B.',
    customerPhone: '+213559678901',
    deliveredKey: 'https://jioai.pro/activate?token=jio-act-dz-116',
    notes: 'Jio AI Pro - Réduction fidélité appliquée',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T23:05:00.000Z',
  },

  // --- EXACTLY 7 WAITING PAYMENTS FOR JIO AI PRO @ 1400 DZD (Crédit / Pay Later - Non confirmés) ---
  {
    id: 'sale-pending-1',
    saleNumber: '#1017',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'pending',
    pendingNote: 'Client Karim B. - promis ce soir par BaridiMob (1400 DA)',
    customerName: 'Karim B.',
    customerPhone: '+213551234567',
    deliveredKey: 'https://jioai.pro/activate?token=jio-pend-01',
    exchangeRateUsed: 242,
    createdAt: '2026-09-11T23:30:00.000Z',
  },
  {
    id: 'sale-pending-2',
    saleNumber: '#1018',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Abdou',
    paymentMethod: 'baridimob',
    paymentStatus: 'pending',
    pendingNote: 'Client Sofiane M. - lien envoyé, attend virement BaridiMob',
    customerName: 'Sofiane M.',
    customerPhone: '+213662345678',
    deliveredKey: 'https://jioai.pro/activate?token=jio-pend-02',
    exchangeRateUsed: 242,
    createdAt: '2026-09-12T00:15:00.000Z',
  },
  {
    id: 'sale-pending-3',
    saleNumber: '#1019',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'pending',
    pendingNote: 'Client Yacine T. - promis par BaridiMob demain matin',
    customerName: 'Yacine T.',
    customerPhone: '+213773456789',
    deliveredKey: 'https://jioai.pro/activate?token=jio-pend-03',
    exchangeRateUsed: 242,
    createdAt: '2026-09-12T00:50:00.000Z',
  },
  {
    id: 'sale-pending-4',
    saleNumber: '#1020',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Abdou',
    paymentMethod: 'baridimob',
    paymentStatus: 'pending',
    pendingNote: 'Client Amine K. - virement BaridiMob en cours de validation',
    customerName: 'Amine K.',
    customerPhone: '+213541122334',
    deliveredKey: 'https://jioai.pro/activate?token=jio-pend-04',
    exchangeRateUsed: 242,
    createdAt: '2026-09-12T01:25:00.000Z',
  },
  {
    id: 'sale-pending-5',
    saleNumber: '#1021',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'pending',
    pendingNote: 'Client Walid R. - compte activé, paiera plus tard (1400 DA)',
    customerName: 'Walid R.',
    customerPhone: '+213698765432',
    deliveredKey: 'https://jioai.pro/activate?token=jio-pend-05',
    exchangeRateUsed: 242,
    createdAt: '2026-09-12T02:00:00.000Z',
  },
  {
    id: 'sale-pending-6',
    saleNumber: '#1022',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Abdou',
    paymentMethod: 'baridimob',
    paymentStatus: 'pending',
    pendingNote: 'Client Nabil H. - reçu en attente de vérification',
    customerName: 'Nabil H.',
    customerPhone: '+213789012345',
    deliveredKey: 'https://jioai.pro/activate?token=jio-pend-06',
    exchangeRateUsed: 242,
    createdAt: '2026-09-12T02:35:00.000Z',
  },
  {
    id: 'sale-pending-7',
    saleNumber: '#1023',
    productName: 'Jio AI Pro',
    productId: 'prod-jio-ai-pro',
    sellingPriceDzd: 1400,
    productCostUsd: 0,
    netProfitDzd: 1400,
    soldBy: 'Adem',
    paymentMethod: 'baridimob',
    paymentStatus: 'pending',
    pendingNote: 'Client Farid D. - crédit accordé jusqu’à dimanche (1400 DA)',
    customerName: 'Farid D.',
    customerPhone: '+213555667788',
    deliveredKey: 'https://jioai.pro/activate?token=jio-pend-07',
    exchangeRateUsed: 242,
    createdAt: '2026-09-12T03:10:00.000Z',
  },
];

// Active 24-Hour Caisse shift matching current BaridiMob capital float (22,345 DZD)
export const INITIAL_CAISSES: DailyCaisse[] = [
  {
    id: 'caisse-2026-09-12',
    date: '2026-09-12',
    status: 'open',
    openedAt: '2026-09-12T00:00:00.000Z',
    openedBy: 'Adem',
    initialBalanceDzd: 22345, // BaridiMob current capital
    initialBalanceUsd: 150,
    notes: 'Shift 24h actif. Fonds BaridiMob (22,345 DA profit net Jio AI Pro).',
  },
];
